# !!! WARNING !!!
#
# This file should NOT be pulled into the production site since it sets specific site variables necessary to make the site work in non-production environments.
#

name: TianoCore
description: TianoCore UEFI related projects

# Can't define 'url' on non-production GH pages as it will mess up 'redirect_from'
#url: http://www.tianocore.org
url: https://acgmultimedia.github.io/acgtianocore

# If hosting a project on GH pages, must define a baseurl to the project
#baseurl: /acgtianocore

markdown: kramdown

highlighter: rouge

gems:
  - jekyll-redirect-from